gurushree/gurushree/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('api/masters/', include('masters.urls')),
    path('api/trans/', include('transactions.urls')),
    path('api/auth/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gurushree/pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('dashboard', views.dashboard, name='register'),
    path('masters/departments', views.departments, name='departments'),
    path('masters/Places', views.places, name='places'),
    path('masters/Generals', views.generals, name='generals'),
    path('masters/GenTypes', views.genTypes, name='genTypes'),
    path('masters/distypes', views.disType, name='disTypes'),
    path('masters/RegTypes', views.regTypes, name='regtypes'),
    path('masters/Pages', views.pages, name='pages'),
    path('masters/menus', views.menus, name='menus'),
    path('masters/incomeExpenses', views.incomeExpenses, name='incomeExpenses'),
    path('masters/hospitals', views.hospitals, name='hospitals'),
    path('masters/users', views.users, name='users'),
    path('masters/professionals', views.professionals, name='professionals'),
    path('masters/services', views.services, name='services'),
    path('masters/packagemaping', views.packagemap, name='packagemaping'),
    path('trans/patientReg', views.patientReg, name='patientReg'),
    path('trans/op_billing', views.op_billing, name='op_billing'),
]

gurushree/templates/partials/_head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gurushree Hospital</title>

    <link href="{% static 'admin/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="{% static 'admin/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'admin/css/file.css' %}" rel="stylesheet">
    <link href="{% static 'admin/css/toastr.min.css' %}" rel="stylesheet">

    <link href="{% static 'admin/css/typeahead.css' %}" rel="stylesheet">
    <link href="{% static 'admin/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <!--<link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link>-->
    <link href="{% static 'admin/css/styles.css' %}" rel="stylesheet">
</head>

gurushree/templates/partials/_navbar.html
<ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/dashboard">
        <div class="sidebar-brand-icon">
            <i class="fas fa-plus-circle"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Gurushree Hospital<sup></sup></div>
    </a>


    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/dashboard">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMasters" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-database"></i>
            <span>Masters</span>
        </a>
        <div id="collapseMasters" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'pages:generals'%}">Generals</a>
                <a class="collapse-item" href="{% url 'pages:departments'%}">Departments</a>
                <a class="collapse-item" href="{% url 'pages:places'%}">Places</a>
                <a class="collapse-item" href="{% url 'pages:regtypes'%}">Registration Types</a>
                <a class="collapse-item" href="{% url 'pages:incomeExpenses'%}">Income & Expenses</a>
                <a class="collapse-item" href="{% url 'pages:menus'%}">Menus</a>
                <a class="collapse-item" href="{% url 'pages:pages'%}">Pages</a>
                <a class="collapse-item" href="{% url 'pages:users'%}">Users</a>
                <a class="collapse-item" href="{% url 'pages:hospitals'%}">Hospitals</a>
                <a class="collapse-item" href="{% url 'pages:professionals' %}">Professionals</a>
                <a class="collapse-item" href="{% url 'pages:services' %}">Services</a>
                <a class="collapse-item" href="{% url 'pages:packagemaping' %}">Package Maping</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTrans" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Transactions</span>
        </a>
        <div id="collapseTrans" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item spl-item" href="{% url 'pages:patientReg' %}">Patient Registration</a>
            </div>
        </div>
    </li>



    <!-- Nav Item - Charts -->


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->


</ul>

gurushree/templates/partials/_scripts.html
{% load static %}
<script src="{% static 'admin/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'admin/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'admin/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'admin/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'admin/vendor/jquery/jquery.validate.min.js' %}"></script>
<script src="{% static 'admin/js/sb-admin-2.js' %}"></script>
<script src="{% static 'admin/js/toastr.min.js' %}"></script>
<script src="{% static 'admin/js/file.js' %}"></script>
<script src="{% static 'admin/js/jquery.cookie.js' %}"></script>
<script src="{% static 'admin/js/typeahead.bundle.js' %}"></script>
<script src="http://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>